#! /bin/sh

bspc config border_width        2
bspc config window_gap         10
bspc config top_padding        16
bspc config right_padding     214

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV

bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a Steam floating=on
panel &
